[package]
name = "doe-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doe = { version = "1.1.8", features = ["keyboard", "kcm"] }
